import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ClientOnly from "./../components/ClientsOnly/ClientsOnly";
import TelegramPopupButton from "./../components/PopupButton/TeligramPopupButton";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Logic Trade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black ${poppins.variable} `}>
        <ClientOnly>
          {" "}
          <>
            {children}
            <TelegramPopupButton />
          </>
        </ClientOnly>
      </body>
    </html>
  );
}
